Cloud-CV/Fabrik

- requirements.txt
@deshraj Please review this PR.
> Updated the protobuf version to >=3.0 in requirements

- requirements.txt
fixes #26 . @deshraj @virajprabhu Please review the PR.
> Updated Requirements: Added Tensorflow in requirements.

- ide/settings.py
- ide/urls.py
- requirements.txt
> Add django-allauth to IDE

- README.md
@virajprabhu please review & let me know the changes if any!
> Fix: Added Tensorflow version hint for conda(#33)

- caffe_app/views/import_prototxt.py
- ide/static/bundle/bundle.js
- ide/static/js/content.js
- ide/static/js/topBar.js
Added support for static sharing as discussed in #17
> added static sharing

- .travis.yml
- requirements.txt
- python codes checked for PEP8 standard
- updated tensorflow version in requirements.txt to oldest supported one
- pep8 and flake8 added to requirements.txt
> Python dependencies added to travis

- caffe_app/views/import_prototxt.py
* Some convolution parameters were missing values when loading an exported prototxt
* These parameters were not checked for another parameter name with the same purpose
Fixes #69
> Fixed issue with importing prototxt exported from Fabrik

- README.md
The screenshots were linked to a branch in my fork, changed them to refer to the master branch.
> Changed links to screenshots

- ide/static/bundle/bundle.js
- ide/static/js/topBar.js
* Allows only '.prototxt' file for Caffe
* Allows only '.pbtxt' file for Tensorflow
> Added file format restriction for upload

- example/caffe/All_CNN.prototxt
- ide/static/js/topBar.js
@utsavgarg I tested All-CNN model from https://github.com/mateuszbuda/ALL-CNN it works.
> Fix #30: Add All-CNN model to Fabrik/Zoo

- example/caffe/Squeezenet.prototxt
- ide/static/js/topBar.js
@utsavgarg Squeeezenet Model Tested & Added.
> Fix: Add Squeezenet model to FabrikZoo (#105)

- example/keras/textGeneration.json
- ide/static/js/data.js
- ide/static/js/topBar.js
- keras_app/views/layers_export.py
- keras_app/views/layers_import.py
@dexter1691 @virajprabhu Large LSTM network for Text Generation using keras.
https://machinelearningmastery.com/text-generation-lstm-recurrent-neural-networks-python-keras/
https://github.com/Ram81/Deep_Learning_Models/blob/master/lstm_text_generation.py
> Fix: Add Text Generation model for Keras LSTM Demo (#115)

- ide/static/js/content.js
@utsavgarg @deshraj please review
Existing Behaviour
Updated Behaviour
Above model is Inception V3
> Fix: Handling Visualisation to avoid Overlapping Layers

- README.md
- example/keras/seq2seq_lang.json
- ide/static/js/canvas.js
- ide/static/js/content.js
- ide/static/js/topBar.js
- requirements/caffe_tensorflow_keras_install.sh
- requirements/common.txt
- tests/unit/keras_app/test_views.py
The neural network translates English to French. The model is
taken from https://github.com/fchollet/keras/blob/master/examples/lstm_seq2seq.py
Changed `caffe_tensorflow_keras_install.sh` to install latest
version of keras.
Fixes https://github.com/Cloud-CV/Fabrik/issues/124
Note: Keras version 2.0.8 ~~and Tensorflow version 1.3.0~~ is needed
for this model to work.
> FIX (#124): Added seq2seq model for translation in Model Zoo

- caffe_app/views/import_prototxt.py
@utsavgarg as we don't consider stage arguments I thought a proper check for phase type is needed, plus it helped with the problem of separating phases in Visualisation issue #127 
Please review
> Fix: Improve Check for Type of Phase

- example/caffe/CoCo_Caption.prototxt
- ide/static/js/topBar.js
@virajprabhu @dexter1691 #115 Fixed.
Here is the link for the model https://github.com/jeffdonahue/caffe/blob/recurrent-rebase-cleanup/examples/coco_caption/lstm_language_model.prototxt
> Fix: CoCo Caption model added to demonstrate use of LSTM Layer (#115)

- example/caffe/yolo_net.prototxt
- ide/static/js/topBar.js
@utsavgarg Object Detection model added.
Reference: https://github.com/xingwangsfu/caffe-yolo/blob/master/prototxt/yolo_deploy.prototxt
> Fix: Added YOLONet Object Detection Model

- ide/templates/index.html
Change path from "/images/favicon.ico" to "/static/img/favicon.ico".
> Minor fix : favicon path

- ide/static/css/style.css
- ide/static/js/content.js
@virajprabhu @utsavgarg please review.
> Fix: Add Overlay to Loader for Model Export(#111)

- ide/static/js/content.js
Can not load shared model.
Fix broken url in model share
> Fix : Broken Share URL

- example/caffe/CoCo_Caption.prototxt
- ide/static/css/style.css
> Fix: Update COCO caption model to include Dropout Layer

- ide/templates/index.html
> Google Analytics Implementation

- README.md
Added more installation instructions for users running Ubuntu-based operating systems.
> Added specific installation instructions in README.md 

- ide/utils/jsonToPrototxt.py
Change Caffe implementation to be modular like Keras implementation
> Make json_to_prototxt.py modular

- ide/static/css/style.css
- ide/static/js/content.js
- ide/static/js/modelElement.js
- ide/static/js/topBar.js
Changed the Fabrik model zoo UI from dropdown to a modal with classifications.
> Changed UI for the Fabrik model zoo.

- README.md
Proper usage from sudoing into another user should be -i . Just a -u  throws an error.
> Update README - sudo -u -> sudo -i -u

- ide/static/js/canvas.js
- ide/static/js/content.js
- ide/static/js/pane.js
- ide/static/js/paneElement.js
If you have concerns, it works on my local version.
> On click, a new layer connects to bottom of node if possible.

- caffe_app/views/import_prototxt.py
- ide/utils/jsonToPrototxt.py
PR to refactor the caffe app implementation to make it more modular.
> Make caffe app modular

- ide/static/js/jsplumb.js
Please let me know what to change,
Thanks.
> changed viz algo to avoid cutting nodes

- ide/static/css/style.css
- ide/static/js/canvas.js
- ide/static/js/content.js
- ide/static/js/panZoom.js
- ide/static/js/topBar.js
The default name for a net is Untitled. When a net is loaded from the model zoo, its name is loaded into the textbox provided, which can be changed, and the changed name will be reflected in the exported file.
> Fix #117: Add a title pane

- caffe_app/views/import_prototxt.py
- ide/static/css/style.css
- ide/static/js/canvas.js
- ide/static/js/content.js
- ide/urls.py
- ide/utils/shapes.py
- ide/views.py
- keras_app/views/export_json.py
- tests/unit/keras_app/test_views.py
@utsavgarg its the initial work for #126.
> Fix: Show Total Parameters of Model Visualized(#126)

- ide/static/js/content.js
The endPoint property seems to be causing problems, as this information is Fabrik-specific and not related to Caffe.
> Fix #184: Export fails after layer is added

- caffe_app/views/import_prototxt.py
- ide/static/css/style.css
- ide/static/js/content.js
- keras_app/views/export_json.py
- tests/unit/caffe_app/test_views.py
Now it show why is prototxt invalid and unknown layers.
> More detailed error messages

- docs/source/tested_models.md
- example/caffe/pix2pix.prototxt
- ide/static/js/modelZoo.js
- tutorials/tested_models.md
Add Pix2Pix model: Image-to-image translation with conditional adversarial nets.
Partial Fix: https://github.com/Cloud-CV/Fabrik/issues/30
Related GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5243398514540544/
> Add Pix2Pix model to the Fabrik model zoo

- caffe_app/views/import_prototxt.py
It works but needs 'silent' option.
> Auto-upgrade old prototxt

- docs/source/UIDocumentation.md
I've created a PR for UI documentation, it's a WIP and I will expand on it. 
I wanted to see if there was a specific preference for the automation for the JS documentation, otherwise I will add in the script I am using to generate the method and param information. 
Thanks and please give me some feedback so we can make this documentation excellent!
> UI documentation : WIP

- caffe_app/views/import_prototxt.py
- ide/static/css/style.css
- ide/static/js/content.js
- ide/static/js/importTextbox.js
- ide/static/js/topBar.js
- keras_app/views/import_json.py
- tensorflow_app/views/import_graphdef.py
- tests/unit/caffe_app/test_views.py
- tests/unit/keras_app/test_views.py
For Code-In task: https://codein.withgoogle.com/dashboard/task-instances/5870321804509184/
> Import model via text input

- tutorials/tested_models.md
Added Visualise link to VQA model.
@utsavgarg
> Added Visualise to VQA

- tutorials/tested_models.md
Done as required. Added the tested models.
> Added Tested Models

- ide/static/js/canvas.js
- ide/static/js/panZoom.js
> Disabled buttons and zooming without network fix

- ide/static/js/canvas.js
- ide/static/js/content.js
- ide/static/js/setParams.js
- ide/urls.py
- ide/utils/shapes.py
- ide/views.py
> Fix: Update Total Parameter for layer add and delete(#126)

- ide/static/js/content.js
@deshraj @utsavgarg Fixes #278
> Fix: Disable shareable feature when canvas is empty(#278)

- caffe_app/views/import_prototxt.py
- ide/static/css/style.css
- ide/static/js/content.js
- ide/static/js/topBar.js
- ide/static/js/urlImportModal.js
- keras_app/views/import_json.py
- tensorflow_app/views/import_graphdef.py
- tests/unit/caffe_app/test_views.py
- tests/unit/keras_app/test_views.py
> Load model from url

- docs/source/tested_models.md
- example/keras/ZF_UNET_224.json
- ide/static/js/modelZoo.js
- tutorials/tested_models.md
I added [UNET](https://github.com/ZFTurbo/ZF_UNET_224_Pretrained_Model) to the Model Zoo, this is a screenshot:
I've also made sure that I can export it successfully.
> Add UNET to The Model Zoo

- ide/static/js/content.js
@utsavgarg minor fixes to avoid unnecessary error while fetching total number of parameters of a layer.
> Fix: Add check for layer shape in parameter calculation

- ide/utils/shapes.py
@utsavgarg try importing googlenet in tensorflow and see the shape of Flatten Layer,I added a check to avoid miscalculations.
> Fix: Flatten Layer Shape Miscalculation logic corrected

- example/caffe/simpleNet.prototxt
- ide/static/js/modelZoo.js
- tutorials/tested_models.md
Fix: #105 Added SimpleNet 101 model(close to state of art model in classification in terms of less parameters).
> Add SimpleNet model to FabrikZoo( #105)

- ide/utils/shapes.py
- ide/views.py
> Fix: Dim Error when adding input layers (#285)

- README.md
> Add tested models table in Readme

- ide/utils/shapes.py
@deshraj @utsavgarg This PR optimizes the implementation of topological sort for Shape Calculation module.
> Optimize Topological Sort for Shape Calculation

- example/tensorflow/Conv3DCheck.pbtxt
- ide/static/js/canvas.js
- ide/static/js/content.js
- ide/static/js/jsplumb.js
- ide/static/js/layer.js
- tensorflow_app/views/import_graphdef.py
- tests/unit/tensorflow_app/test_views.py
@deshraj @utsavgarg This PR adds support for 3D Conv layer + import test.
> Add Support for 3D Convolution Layer

- ide/static/js/canvas.js
@utsavgarg @interritus1996 @kdexd Fixes layer shape ui bugs.
> Fix: Layer Shape UI

- ide/static/js/pane.js
@ayshrv @utsavgarg @kdexd  this PR adds depthwise conv layer to UI sidebar.
> Add Depthwise Convolution to Sidebar UI

- .gitignore
- ide/__init__.py
- ide/celery.py
- requirements/common.txt
- settings/common.py
@deshraj @utsavgarg @ayshrv @kdexd  This PR adds setup of celery.
> Add Celery Setup

- README.md
- tutorials/keras_custom_layer_usage.md
Updated README.md for tested models (AlexNet/Keras). The only change needed is while importing the LRN layer, pass it as a dictionary (more info here : https://github.com/keras-team/keras/issues/8612)
> Updated README.md for tested models (AlexNet/Keras)

- .travis.yml
- README.md
- docker/dev/reactjs/Dockerfile
- webpack.config.js
This PR fixes issue with webpack setup in docker. Testing in progress.
> Fix issue in docker setup for reactjs

- ide/static/js/content.js
> Fix: Webpack style fix in content.js

- ide/static/css/login_style.css
- ide/static/js/content.js
- ide/static/js/login.js
> Fix style issues with login panel (Duplicate)

- ide/static/js/canvas.js
- ide/static/js/layer.js
> GCI: Fix the layer choppiness (lag) when a layer is dragged.

- tensorflow_upgrade.md
GCI [Task](https://codein.withgoogle.com/dashboard/task-instances/6595974689456128/): Upgrade TensorFlow to a higher version
This PR simply adds the markdown file explaining the tensorflow upgrade.
#429 - Updated Requirements.
> Tensorflow upgrade documentation

- caffe_app/consumers.py
GCI [Task](https://codein.withgoogle.com/dashboard/task-instances/5882688117407744/): Refactor backend codebase of Real Time Collaboration feature
> GCI: Refactored consumers.py

- README.md
IMPORTANT NOTES (please read and then delete):
* The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: Changed UI layout from horizontal to vertical.".
* Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables Github to link the PR to the corresponding bug.
Please also make sure to follow the [contribution](https://github.com/Cloud-CV/Fabrik/blob/master/.github/CONTRIBUTING.md) guidelines.
> Read and fix grammatical or spelling errors in the readme.md

- README.md
* Added badge for documentation
> Added badge for documentation
