Cloud-CV/Fabrik

- caffe_app/views/import_prototxt.py
- ide/static/bundle/bundle.js
- ide/static/js/data.js
- ide/utils/jsonToPrototxt.py
* The dropout param 'inplace' was never set during import
* And 'inplace' was not part of the dropout node definition
Fixes issue #53
> Fixed issue with exporting networks with Dropout

- ide/static/js/canvas.js
```js
if (layer.info.type == 'Python'){
// Changing endpoints depending on the type of Python layer
if (layer.params.endPoint[0] == '1, 0'){
data[layer.info.type]['endpoint']['trg'] = [];
data[layer.info.type]['endpoint']['src'] = ['Bottom'];
}
else if (layer.params.endPoint[0] == '0, 1'){
data[layer.info.type]['endpoint']['trg'] = ['Top'];
data[layer.info.type]['endpoint']['src'] = [];
}
else{
data[layer.info.type]['endpoint']['trg'] = ['Top'];
data[layer.info.type]['endpoint']['src'] = ['Bottom'];
}
if (layer.params){
Object.keys(layer.params).forEach(param => {
if (param != 'endPoint'){
data[layer.info.type]['params'][param] = {'name': param, 'type': 'text',
'required': false, 'value': ''};
}
});
}
}
```
I handled this bug. The endpoint object does not exist in params, so It causes …
> FIX #148: Python ModelElement TypeError solve 

- ide/static/css/style.css
- ide/static/js/content.js
Google Code-In task. When screen width <= 1200px, sidebar cannot be accommodated on screen permanently. Here the sidebar is collapsed by default on such screens and a hamburger menu icon is present to show it.
> Collapse sidebar on small screens

- docs/source/index.rst
- docs/source/keras_json_usage.md
- docs/source/setup.md
- docs/source/tested_models.md
Adds all available documentation to the fabrik's readthedocs site.
You can check the site of my fork here: http://fabrikdocs.readthedocs.io/
Related GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5050072960073728/
> Host all documentation on readthedocs

- ide/static/js/pane.js
`toggleClass()` now iterates over all categories and sets the real state from `aria-expanded` attribute to each var in this.state.
> Fix #188: Collapsibles' arrows

- ide/static/css/style.css
- ide/static/js/content.js
> Fix: title no longer overlaps with error messages, if any.

- ide/static/js/canvas.js
- ide/static/js/content.js
- ide/static/js/pane.js
There was a problem `deleteLayer()` in `content.js`. `nextLayerId` stayed the same even after the last layer was deleted. My fix substracts 1 from nextLayerId if last layer was deleted.
~~There are still some issues when layer in middle is deleted, you can't delete layers in the separated part of the net anymore. You can still add layers to the end tho.~~
edit: It's actually a problem of indexing. Some methods expected that the layers will be in a sequence (no index missing). Deleting a layer caused missing index which caused the bug.
> Fix #199: Cannot add layer after delete

- ide/static/js/content.js
This code changes the behavior when the frontend gets a 500 error from the backend, it throws an error now, rather than just infinitely hanging on a loading screen.
I am getting a mixed tabs and spaces error though, what would be the easiest way to fix it? Are there automated tools to fix it?
> Error Message on 500 error from backend while exporting. 

- ide/static/js/setParams.js
Deleting a lot of layers can get annoying because we have to select each one and click the delete layer button. 
I made this process more convenient, and now pressing the delete key with a layer selected will delete that layer.
> Feature Addition: Delete Selected Layers by pressing delete key

- caffe_app/views/import_prototxt.py
- ide/static/css/style.css
- ide/static/js/canvas.js
- ide/static/js/content.js
- ide/static/js/pane.js
- ide/static/js/paneElement.js
**Issue 1: Dragging/dropping layers did not work:**
This issue was caused due to the spec set for setData/getData in drag-drop events, where the data is stored in a "protected mode", ie. no event other than the original one is allowed to access it. Firefox and Chrome don't follow the W3C spec so setData/getData works there, but Edge follows the spec and doesn't allow it.
More info here: https://stackoverflow.com/questions/11927309/html5-dnd-datatransfer-setdata-or-getdata-not-working-in-every-browser-except-fi
The most effective solution is to just use a different means of storing what is being dragged or dropped, so I used a React state variable.
**Issue 2: Models could not be imported from file:**
This seems to have been caused due to the fact that while every other browser sends a …
> Fix #198: Fabrik now works on Edge

- ide/static/js/content.js
This is parallel to #190, for the share link button instead of the export button.
For now I have made the same change here, but maybe we could look into separating this code into its own function and call saveDb() and exportNet() as a callback, so we don't have to maintain the code in two places?
> Fix and commonize export prep

- caffe_app/views/import_prototxt.py
- ide/static/js/data.js
- keras_app/views/layers_import.py
- tensorflow_app/views/import_graphdef.py
> Fix: Extended Support for Layer Import for  TF and keras (#293)

- requirements/caffe_tensorflow_keras_install.sh
fixes #306 
shellscript wipe present entries in bash_profile while setting PYTHONPATH, modifying it to only append at the end of bash_profile instead of deleting present entries.
> Fix #306:changed shellscript to append new entries into `bash_profile` instead of wiping and rewriting the file

- tensorflow_app/views/import_graphdef.py
@utsavgarg minor correction in batchnorm layer now resnet shape calculation works fine and support leakyrelu as we are using same frontend for leakyrelu and relu.
> TF import support

- .travis.yml
- README.md
- requirements/caffe_tensorflow_keras_install.sh
- tensorflow_app/views/import_graphdef.py
- tests/unit/keras_app/test_views.py
**Update:**
- Added an extra dependency for TensorFlow installation, and exported a variable to fix the build error.
**Change Log:** (Only the TF Backend part of #309)
- Fixed a failing unittest while using TensorFlow backend for Keras.
- Added code to reset graph before importing, in tensorflow_app/views/**import_graphdef.py**
- Added unittest for testing dimension ordering (channels last/first) . By default, in our case, the channels last ordering is used for both Theano and TensorFlow. The unittest is used to verify the same.
- Modified all import unittests, and a line in import_graphdef.py, to use channels last ordering, as it should be. The export tests only tests if the layer's name is correct, so it was left intact.
- Modified README to change server deploying instruction to use …
> Keras TF Backend Support

- example/keras/v4.json
- ide/static/js/modelZoo.js
- tutorials/tested_models.md
This PR is for the addition of Inception_v4 model to the Zoo.
It is fundamentally different from v3 , as it has Resnets combined with Inception architecture.
As described in the paper
https://arxiv.org/abs/1602.07261
Please review
> Addition of Inception v4 to the Zoo

- package.json
Originally, #363 used the react social login buttons for the icons for homepage, but now it is switched to Font-Awesome, so it is no longer needed
> Update package.json - Remove extraneous package.

- backendAPI/views.py
- caffe_app/consumers.py
- caffe_app/models.py
- ide/static/css/style.css
- ide/static/js/CommentSidebar.js
- ide/static/js/UserProfile.js
- ide/static/js/addCommentModal.js
- ide/static/js/canvas.js
- ide/static/js/commentTooltip.js
- ide/static/js/content.js
- ide/static/js/layer.js
- ide/static/js/login.js
- ide/static/js/setParams.js
- ide/static/js/updateHistoryModal.js
- ide/views.py
> WIP: Optimize RTC Updates and RTC Highlighting

- docs/source/tested_models.md
- tutorials/tested_models.md
Just saw this and thought I'd fix it.
> Fix broken markdown link in tested_models.md

- ide/static/js/pane.js
As noted in #418, Slice layer was not added to `pane.js` despite having been defined in `data.js` and the `caffe_app` files. This PR adds the layer to `pane.js`
> Added Slice layer to pane.js

- ide/templates/index.html
Fixed "Web Browser XSS Protection Not Enabled" and "X-Content-Type-Options Header Missing"
The HTTP library (Node) was used to resolve this issue. I used the response function to set the HTTP header.
> Edits of index.html to protect against XSS and MIME attacks

- docs/source/UIDocumentation.md
I updated the UIdocumentation.md to include new features and reviewed the previous version.
> Updated UIdocumentation.md
